language: php
php:
  - 7.2

fast_finish: true

before_script:
  - composer install --no-progress

script:
  - ./bin/phing
  - ./bin/php-coveralls -x build/logs/clover.xml
after_success:
  - ./bin/php-coveralls -v

branches:
  only:
    - master
    - stable
